name: Build Firmware

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'firmware/**'
      - '.github/workflows/build-firmware.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'firmware/**'
      - '.github/workflows/build-firmware.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-pio-
          
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        
    - name: Build firmware
      run: |
        cd firmware
        pio run
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware-build
        path: |
          firmware/.pio/build/**/firmware.bin
          firmware/.pio/build/**/firmware.elf
          firmware/.pio/build/**/firmware.hex
        retention-days: 30
        
    - name: Check firmware size
      run: |
        cd firmware
        pio run --target size 